== The Internals of Spark SQL (Apache Spark {{ book.version }})

Welcome to *The Internals of Spark SQL* gitbook! I'm very excited to have you here and hope you will enjoy exploring the internals of Spark SQL as much as I have.

[quote, Flannery O'Connor]
I write to discover what I know.

I'm https://pl.linkedin.com/in/jaceklaskowski[Jacek Laskowski], an independent consultant, software developer and technical instructor specializing in *Apache Spark*, Apache Kafka and Kafka Streams (with Scala, sbt, Kubernetes, DC/OS, Apache Mesos, and Hadoop YARN).

I offer software development and consultancy services with https://github.com/jaceklaskowski/spark-workshop/blob/gh-pages/slides/README.md#toc[very hands-on in-depth workshops] and mentoring. Reach out to me at jacek@japila.pl or https://twitter.com/jaceklaskowski[@jaceklaskowski] to discuss opportunities.

Consider joining me at http://www.meetup.com/WarsawScala/[Warsaw Scala Enthusiasts] and http://www.meetup.com/Warsaw-Spark[Warsaw Spark] meetups in Warsaw, Poland.

TIP: I'm also writing other books in the "The Internals of" series about https://bit.ly/apache-spark-internals[Apache Spark], https://bit.ly/kafka-streams-internals[Kafka Streams], https://bit.ly/apache-kafka-internals[Apache Kafka] and https://bit.ly/spark-structured-streaming[Spark Structured Streaming].

Expect text and code snippets from a variety of public sources. Attribution follows.

Now, let me introduce you to <<spark-sql.adoc#, Spark SQL>>.
