site_name: The Internals of Spark SQL
site_url: https://books.japila.pl/spark-sql-internals
site_author: Jacek Laskowski
site_description: Demystifying inner-workings of Spark SQL

repo_name: Github
repo_url: https://github.com/japila-books/spark-sql-internals
edit_uri: edit/main/docs/

copyright: Copyright &copy; 2026 Jacek Laskowski

theme:
  name: material
  language: en
  icon:
    logo: material/book-open-page-variant
    repo: material/github
  features:
    # https://squidfunk.github.io/mkdocs-material/reference/code-blocks/#adding-annotations
    - content.code.annotate
    # https://squidfunk.github.io/mkdocs-material/upgrade/#contentcodecopy
    - content.code.copy
    # https://squidfunk.github.io/mkdocs-material/reference/content-tabs/#linked-content-tabs
    - content.tabs.link
    - content.tooltips
    - navigation.indexes
    - navigation.instant
    # https://squidfunk.github.io/mkdocs-material/setup/setting-up-navigation/#navigation-path
    - navigation.path
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.top
    - navigation.tracking
    - search.highlight
    - search.share
    - search.suggest
    - toc.follow
  palette:
    - media: "(prefers-color-scheme)"
      toggle:
        icon: material/brightness-auto
        name: Switch to light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      toggle:
        icon: material/brightness-4
        name: Switch to system preference

markdown_extensions:
  - admonition
  - attr_list
  - footnotes
  - md_in_html
  - toc:
      permalink: true
  - pymdownx.arithmatex
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.caret
  - pymdownx.critic
  - pymdownx.details
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - pymdownx.inlinehilite
  - pymdownx.magiclink
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.superfences
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.tilde

plugins:
  # https://lukasgeiter.github.io/mkdocs-awesome-nav/migration-v3/
  - awesome-nav
  - macros
  # https://squidfunk.github.io/mkdocs-material/reference/#built-in-meta-plugin
  - meta
  - minify:
      minify_html: true
  # https://github.com/mkdocs/mkdocs-redirects
  - redirects:
      redirect_maps:
          'datasources/index.md': 'connectors/index.md'
  - search
  # https://squidfunk.github.io/mkdocs-material/setup/setting-up-tags/
  - tags:
      enabled: !ENV [CI, false]
      tags_extra_files:
        developer-api.md:
          - DeveloperApi
  # https://squidfunk.github.io/mkdocs-material/reference/#built-in-typeset-plugin
  - typeset

extra:
  analytics:
    provider: google
    property: !ENV GOOGLE_ANALYTICS_KEY
  book:
    title: Spark SQL
    delta: https://books.japila.pl/delta-lake-internals
    kafka: https://books.japila.pl/kafka-internals
    pyspark: https://books.japila.pl/pyspark-internals
    spark_core: https://books.japila.pl/apache-spark-internals
    spark_connect: https://books.japila.pl/spark-connect-internals
    structured_streaming: https://books.japila.pl/spark-structured-streaming-internals
  hadoop:
    # https://github.com/apache/spark/blob/v4.1.1/pom.xml#L130
    version: 3.4.2
    docs: https://hadoop.apache.org/docs/r3.4.2
    api: https://hadoop.apache.org/docs/r3.4.2/api
  hive:
    # https://github.com/apache/spark/blob/v4.1.1/pom.xml#L139
    version: 2.3.10
    api: https://svn.apache.org/repos/infra/websites/production/hive/content/javadocs/r2.3.10/api
  java:
    # https://github.com/apache/spark/blob/v4.1.1/pom.xml#L120
    version: 17
    api: https://docs.oracle.com/en/java/javase/17/docs/api/java.base
    spec: https://docs.oracle.com/javase/specs/jls/se17/html
  kafka:
    # https://github.com/apache/spark/blob/v4.1.1/pom.xml#L141
    version: 3.9.1
    api: https://kafka.apache.org/39/javadoc
  scala:
    # https://github.com/apache/spark/blob/v4.1.1/pom.xml#L176
    version: 2.13.17
    api: https://www.scala-lang.org/api/2.13.17
    docs: https://docs.scala-lang.org/
    spec: https://www.scala-lang.org/files/archive/spec/2.13
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/jaceklaskowski
    - icon: fontawesome/brands/bluesky
      link: https://bsky.app/profile/books.japila.pl
    - icon: fontawesome/brands/twitter
      link: https://twitter.com/jaceklaskowski
    - icon: fontawesome/brands/linkedin
      link: https://linkedin.com/in/jaceklaskowski
    - icon: fontawesome/brands/medium
      link: https://jaceklaskowski.medium.com
    - icon: fontawesome/brands/mastodon
      link: https://fosstodon.org/@jaceklaskowski
  spark:
    version: 4.1.1
    commit: https://github.com/apache/spark/commit
    docs: https://spark.apache.org/docs/4.1.1
    github: https://github.com/apache/spark/blob/v4.1.1
    jira: https://issues.apache.org/jira/browse
  # https://squidfunk.github.io/mkdocs-material/reference/#setting-the-page-status
  status:
    # There seem to be no use of any other 'new' markers
    # as many 'new's would make the newest less visible
    new: New in 3.5
  # https://squidfunk.github.io/mkdocs-material/setup/setting-up-tags/#tag-icons-and-identifiers
  tags:
    DeveloperApi: developerapi

validation:
  omitted_files: warn
  absolute_links: warn
  unrecognized_links: warn

# nav section is in the separate file ".nav.yml" managed by Awesome Nav for MkDocs plugin
# https://lukasgeiter.github.io/mkdocs-awesome-nav/features/nav/