== [[HiveFileFormat]] HiveFileFormat -- FileFormat For Writing Hive Tables

`HiveFileFormat` is a <<spark-sql-FileFormat.adoc#, FileFormat>> for <<prepareWrite, writing Hive tables>>.

[[shortName]]
`HiveFileFormat` is a <<spark-sql-DataSourceRegister.adoc#, DataSourceRegister>> and <<spark-sql-DataSourceRegister.adoc#shortName, registers itself>> as *hive* data source.

NOTE: Hive data source can only be used with tables and you cannot read or write files of Hive data source directly. Use <<spark-sql-DataFrameReader.adoc#table, DataFrameReader.table>> or <<spark-sql-DataFrameWriter.adoc#saveAsTable, DataFrameWriter.saveAsTable>> for loading from or writing data to Hive data source, respectively.

`HiveFileFormat` is <<creating-instance, created>> exclusively when `SaveAsHiveFile` is requested to <<spark-sql-LogicalPlan-SaveAsHiveFile.adoc#saveAsHiveFile, saveAsHiveFile>> (when <<spark-sql-LogicalPlan-InsertIntoHiveDirCommand.adoc#, InsertIntoHiveDirCommand>> and <<spark-sql-LogicalPlan-InsertIntoHiveTable.adoc#, InsertIntoHiveTable>> logical commands are executed).

[[creating-instance]]
[[fileSinkConf]]
`HiveFileFormat` takes a `FileSinkDesc` when created.

[[inferSchema]]
`HiveFileFormat` throws a `UnsupportedOperationException` when requested to <<spark-sql-FileFormat.adoc#inferSchema, inferSchema>>.

```
inferSchema is not supported for hive data source.
```

=== [[prepareWrite]] Preparing Write Job -- `prepareWrite` Method

[source, scala]
----
prepareWrite(
  sparkSession: SparkSession,
  job: Job,
  options: Map[String, String],
  dataSchema: StructType): OutputWriterFactory
----

NOTE: `prepareWrite` is part of the <<spark-sql-FileFormat.adoc#prepareWrite, FileFormat Contract>> to prepare a write job.

`prepareWrite` sets the *mapred.output.format.class* property to be the `getOutputFileFormatClassName` of the Hive `TableDesc` of the <<fileSinkConf, FileSinkDesc>>.

`prepareWrite` requests the `HiveTableUtil` helper object to `configureJobPropertiesForStorageHandler`.

`prepareWrite` requests the Hive `Utilities` helper object to `copyTableJobPropertiesToConf`.

In the end, `prepareWrite` creates a new `OutputWriterFactory` that creates a new `HiveOutputWriter` when requested for a new `OutputWriter` instance.
