== [[InputPartitionReader]] InputPartitionReader Contract

`InputPartitionReader` is the <<contract, abstraction>> of <<implementations, input partition readers>> that can <<next, proceed to the next record>> and <<get, get the current record>>.

`InputPartitionReader` is also a Java https://docs.oracle.com/javase/8/docs/api/java/io/Closeable.html[Closeable].

`InputPartitionReader` is associated with two other abstractions: <<spark-sql-InputPartition.adoc#, InputPartition>> and `ContinuousInputPartition` that are responsible for creating <<implementations, concrete InputPartitionReaders>>.

NOTE: It _appears_ that all concrete <<implementations, input partition readers>> are used in Spark Structured Streaming only.

[[contract]]
.InputPartitionReader Contract
[cols="30m,70",options="header",width="100%"]
|===
| Method
| Description

| get
a| [[get]]

[source, java]
----
T get()
----

Gets the current record

Used when:

* `DataSourceRDD` is requested to <<spark-sql-DataSourceRDD.adoc#compute, compute a partition>>

* `DataReaderThread` is requested to run (_start up_)

| next
a| [[next]]

[source, java]
----
boolean next()
  throws IOException
----

Proceeds to the next record if available (`true`)

Used when:

* `DataSourceRDD` is requested to <<spark-sql-DataSourceRDD.adoc#compute, compute a partition>>

* `DataReaderThread` is requested to run (_start up_)

|===

[[implementations]]
[[extensions]]
.InputPartitionReaders (Direct Implementations and Extensions Only)
[cols="30m,70",options="header",width="100%"]
|===
| InputPartitionReader
| Description

| ContinuousInputPartitionReader
| [[ContinuousInputPartitionReader]] Extension that is used in Spark Structured Streaming for Continuous Stream Processing

| KafkaMicroBatchInputPartitionReader
a| [[KafkaMicroBatchInputPartitionReader]] Used in Spark Structured Streaming for Kafka Data Source

| MemoryStreamInputPartition
a| [[MemoryStreamInputPartition]] Anonymous that is used in Spark Structured Streaming for Memory Data Source

| RateStreamMicroBatchInputPartitionReader
a| [[RateStreamMicroBatchInputPartitionReader]] Used in Spark Structured Streaming for Rate Data Source

| TextSocketMicroBatchReader
a| [[TextSocketMicroBatchReader]] Anonymous that is used in Spark Structured Streaming for Text Socket Data Source

|===
