== [[JoinSelection]] JoinSelection Execution Planning Strategy

`JoinSelection` is an link:spark-sql-SparkStrategy.adoc[execution planning strategy] that link:spark-sql-SparkPlanner.adoc[SparkPlanner] uses to plan a link:spark-sql-LogicalPlan-Join.adoc[Join] logical operator to one of the supported join physical operators per <<join-selection-requirements, join physical operator selection requirements>>.

[[join-selection-requirements]]
.Join Physical Operator Selection Requirements (in the order of preference)
[cols="1,3",options="header",width="100%"]
|===
| Physical Join Operator
| Selection Requirements

| link:spark-sql-SparkPlan-BroadcastHashJoinExec.adoc[BroadcastHashJoinExec]
a| [[BroadcastHashJoinExec]]

There are joining keys and one of the following holds:

* <<canBuildRight, canBuildRight>> and right join side <<canBroadcast, can be broadcast>>
* <<canBuildLeft, canBuildLeft>> and left join side <<canBroadcast, can be broadcast>>

| link:spark-sql-SparkPlan-ShuffledHashJoinExec.adoc[ShuffledHashJoinExec]
a| [[ShuffledHashJoinExec]]

There are joining keys and one of the following holds:

* link:spark-sql-properties.adoc#spark.sql.join.preferSortMergeJoin[spark.sql.join.preferSortMergeJoin] is disabled, <<canBuildRight, canBuildRight>>, <<canBuildLocalHashMap, canBuildLocalHashMap>> for right join side and finally right join side is <<muchSmaller, much smaller>> than left side

* link:spark-sql-properties.adoc#spark.sql.join.preferSortMergeJoin[spark.sql.join.preferSortMergeJoin] is disabled, <<canBuildLeft, canBuildLeft>>, <<canBuildLocalHashMap, canBuildLocalHashMap>> for left join side and finally left join side is <<muchSmaller, much smaller>> than right

* Left join keys are *not* link:spark-sql-SparkPlan-SortMergeJoinExec.adoc#orderable[orderable]

| link:spark-sql-SparkPlan-SortMergeJoinExec.adoc[SortMergeJoinExec]
| [[SortMergeJoinExec]]

Left join keys link:spark-sql-SparkPlan-SortMergeJoinExec.adoc#orderable[orderable]

| link:spark-sql-SparkPlan-BroadcastNestedLoopJoinExec.adoc[BroadcastNestedLoopJoinExec]
a| [[BroadcastNestedLoopJoinExec]]

There are no joining keys and one of the following holds:

* <<canBuildRight, canBuildRight>> and right join side <<canBroadcast, can be broadcast>>
* <<canBuildLeft, canBuildLeft>> and left join side <<canBroadcast, can be broadcast>>

| `CartesianProductExec`
| [[CartesianProductExec]]

There are no joining keys and link:spark-sql-joins.adoc#join-types[join type] is `INNER` or `CROSS`

| link:spark-sql-SparkPlan-BroadcastNestedLoopJoinExec.adoc[BroadcastNestedLoopJoinExec]
| Default when no other have matched
|===

NOTE: `JoinSelection` uses link:spark-sql-ExtractEquiJoinKeys.adoc[ExtractEquiJoinKeys] Scala extractor to destructure a `Join` logical operator.

=== [[muchSmaller]] Is Left-Side Plan At Least 3 Times Smaller Than Right-Side Plan? -- `muchSmaller` Internal Condition

[source, scala]
----
muchSmaller(a: LogicalPlan, b: LogicalPlan): Boolean
----

`muchSmaller` condition holds when plan `a` is at least 3 times smaller than plan `b`.

Internally, `muchSmaller` link:spark-sql-LogicalPlan.adoc#stats[calculates the estimated statistics for the input logical plans] and compares their physical size in bytes (`sizeInBytes`).

NOTE: `muchSmaller` is used when `JoinSelection` checks <<join-selection-requirements, join selection requirements>> for `ShuffledHashJoinExec` physical operator.

=== [[canBuildLocalHashMap]] `canBuildLocalHashMap` Internal Condition

[source, scala]
----
canBuildLocalHashMap(plan: LogicalPlan): Boolean
----

`canBuildLocalHashMap` condition holds for the logical `plan` whose single partition is small enough to build a hash table (i.e. link:spark-sql-properties.adoc#spark.sql.autoBroadcastJoinThreshold[spark.sql.autoBroadcastJoinThreshold] multiplied by link:spark-sql-properties.adoc#spark.sql.shuffle.partitions[spark.sql.shuffle.partitions]).

Internally, `canBuildLocalHashMap` link:spark-sql-LogicalPlan.adoc#stats[calculates the estimated statistics for the input logical plans] and takes the size in bytes (`sizeInBytes`).

NOTE: `canBuildLocalHashMap` is used when `JoinSelection` checks <<join-selection-requirements, join selection requirements>> for `ShuffledHashJoinExec` physical operator.

=== [[canBuildLeft]] `canBuildLeft` Internal Condition

[source, scala]
----
canBuildLeft(joinType: JoinType): Boolean
----

`canBuildLeft` condition holds for link:spark-sql-joins.adoc#CROSS[CROSS], link:spark-sql-joins.adoc#INNER[INNER] and link:spark-sql-joins.adoc#RIGHT_OUTER[RIGHT OUTER] join types. Otherwise, `canBuildLeft` is `false`.

NOTE: `canBuildLeft` is used when `JoinSelection` checks <<join-selection-requirements, join selection requirements>> for `BroadcastHashJoinExec`, `ShuffledHashJoinExec` or `BroadcastNestedLoopJoinExec` physical operators.

=== [[canBuildRight]] `canBuildRight` Internal Condition

[source, scala]
----
canBuildRight(joinType: JoinType): Boolean
----

`canBuildRight` condition holds for the input `joinType` that is one of the following:

* link:spark-sql-joins.adoc#CROSS[CROSS], link:spark-sql-joins.adoc#INNER[INNER], link:spark-sql-joins.adoc#LEFT_ANTI[LEFT ANTI], link:spark-sql-joins.adoc#LEFT_OUTER[LEFT OUTER], link:spark-sql-joins.adoc#LEFT_SEMI[LEFT SEMI] or link:spark-sql-joins.adoc#ExistenceJoin[ExistenceJoin]

Otherwise, `canBuildRight` is `false`.

NOTE: `canBuildRight` is used when `JoinSelection` checks <<join-selection-requirements, join selection requirements>> for `BroadcastHashJoinExec`, `ShuffledHashJoinExec` or `BroadcastNestedLoopJoinExec` physical operators.

=== [[canBroadcastBySizes]] `canBroadcastBySizes` Internal Method

[source, scala]
----
canBroadcastBySizes(joinType: JoinType, left: LogicalPlan, right: LogicalPlan): Boolean
----

`canBroadcastBySizes`...FIXME

NOTE: `canBroadcastBySizes` is used when `JoinSelection` checks <<join-selection-requirements, join selection requirements>> for `BroadcastHashJoinExec` or `BroadcastNestedLoopJoinExec` physical operators.

=== [[broadcastSideBySizes]] `broadcastSideBySizes` Internal Method

[source, scala]
----
broadcastSideBySizes(joinType: JoinType, left: LogicalPlan, right: LogicalPlan): BuildSide
----

`broadcastSideBySizes`...FIXME

NOTE: `broadcastSideBySizes` is used when `JoinSelection` checks <<join-selection-requirements, join selection requirements>> for `BroadcastHashJoinExec` or `BroadcastNestedLoopJoinExec` physical operators.

=== [[canBroadcast]] Can Logical Plan Be Broadcast? -- `canBroadcast` Internal Condition

[source, scala]
----
canBroadcast(plan: LogicalPlan): Boolean
----

`canBroadcast` is enabled, i.e. `true`, when the size of the output of the input logical plan (aka _sizeInBytes_) is less than link:spark-sql-properties.adoc#spark.sql.autoBroadcastJoinThreshold[spark.sql.autoBroadcastJoinThreshold] configuration property.

NOTE: link:spark-sql-properties.adoc#spark.sql.autoBroadcastJoinThreshold[spark.sql.autoBroadcastJoinThreshold] is 10M by default.

NOTE: `canBroadcast` uses the total size statistic from link:spark-sql-LogicalPlanStats.adoc#stats[Statistics] of a logical operator.

NOTE: `canBroadcast` is used when `JoinSelection` does <<canBroadcastBySizes, canBroadcastBySizes>> and <<broadcastSideBySizes, broadcastSideBySizes>>.

=== [[apply]] Planning Join Logical Operator -- `apply` Method

[source, scala]
----
apply(plan: LogicalPlan): Seq[SparkPlan]
----

NOTE: `apply` is part of link:spark-sql-catalyst-Rule.adoc#apply[Rule Contract] to apply a rule to a link:spark-sql-LogicalPlan.adoc[logical plan] and produce link:spark-sql-SparkPlan.adoc[physical query plans].

`apply` uses link:spark-sql-ExtractEquiJoinKeys.adoc[ExtractEquiJoinKeys] Scala extractor to destructure the input logical `plan`.

`apply` gives a link:spark-sql-SparkPlan-BroadcastHashJoinExec.adoc#creating-instance[BroadcastHashJoinExec] physical operator if <<canBroadcastByHints, canBroadcastByHints>> per the join type and left or right side of the join.

`apply`...FIXME

=== [[canBroadcastByHints]] `canBroadcastByHints` Internal Method

[source, scala]
----
canBroadcastByHints(joinType: JoinType, left: LogicalPlan, right: LogicalPlan): Boolean
----

`canBroadcastByHints` is positive when either condition holds:

. <<canBuildLeft, canBuildLeft>> on the input `joinType` and `left` operator's link:spark-sql-HintInfo.adoc#broadcast[broadcast] hint flag is on

. <<canBuildRight, canBuildRight>> on the input `joinType` and `right` operator's link:spark-sql-HintInfo.adoc#broadcast[broadcast] hint flag is on

NOTE: `canBroadcastByHints` is used when `JoinSelection` is requested to <<apply, plan a Join logical operator>> (and considers a link:spark-sql-SparkPlan-BroadcastHashJoinExec.adoc[BroadcastHashJoinExec] or a link:spark-sql-SparkPlan-BroadcastNestedLoopJoinExec.adoc[BroadcastNestedLoopJoinExec] physical operator).
