== [[FunctionRegistry]] FunctionRegistry

`FunctionRegistry` is a base registry (aka _catalog_) of native and user-defined functions.

NOTE: The one and only `FunctionRegistry` available in Spark SQL is <<SimpleFunctionRegistry, SimpleFunctionRegistry>>.

You can access a session-specific `FunctionRegistry` through link:spark-sql-SessionState.adoc#functionRegistry[SessionState].

[source, scala]
----
val spark: SparkSession = ...
spark.sessionState.functionRegistry
----

NOTE: You can register a new user-defined function using link:spark-sql-UDFRegistration.adoc[UDFRegistration].

[[attributes]]
.FunctionRegistry's Attributes
[width="100%",cols="1,2",options="header"]
|===
| Name
| Description

| [[builtin]] `builtin`
| <<SimpleFunctionRegistry, SimpleFunctionRegistry>> with the <<expressions, built-in functions>> registered.
|===

[[expressions]]
`FunctionRegistry` tracks the mapping between link:spark-sql-Expression.adoc[Catalyst expressions] and their built-in/native SQL functions (that can be used in SQL statements).

.FunctionRegistry's Catalyst Expressions and SQL Functions Mapping
[cols="1,2",options="header",width="100%"]
|===
| Catalyst Expression
| SQL Function

| `IfNull`
| [[ifnull]] `ifnull`

| `Left`
| [[left]] `left`

| `NullIf`
| [[nullif]] `nullif`

| `Nvl`
| [[nvl]] `nvl`

| `Nvl2`
| [[nvl2]] `nvl2`

| `ParseToDate`
| [[to_date]] `to_date`

| link:spark-sql-Expression-ParseToTimestamp.adoc[ParseToTimestamp]
| [[to_timestamp]] `to_timestamp`

| `Right`
| [[right]] `right`

| _others_
|
|===

=== [[expression]] `expression` Internal Method

[source, scala]
----
expression[T <: Expression](name: String)
  (implicit tag: ClassTag[T]): (String, (ExpressionInfo, FunctionBuilder))
----

`expression`...FIXME

NOTE: `expression` is used when...FIXME

=== [[lookupFunction]] `lookupFunction` Method

CAUTION: FIXME

=== [[registerFunction]] `registerFunction` Methods

[source, scala]
----
registerFunction(name: String, builder: FunctionBuilder): Unit  // <1>
registerFunction(name: String, info: ExpressionInfo, builder: FunctionBuilder): Unit
----
<1> Relays calls to the other `registerFunction`

NOTE: `registerFunction` is used when...FIXME

=== [[SimpleFunctionRegistry]] SimpleFunctionRegistry

`SimpleFunctionRegistry` is the default <<FunctionRegistry, FunctionRegistry>> that is backed by a hash map (with optional case sensitivity).
