== [[PullupCorrelatedPredicates]] PullupCorrelatedPredicates Logical Optimization

`PullupCorrelatedPredicates` is a *logical optimization* that <<apply, transforms logical plans>> with the following operators:

. link:spark-sql-LogicalPlan-Filter.adoc[Filter] operators with an link:spark-sql-LogicalPlan-Aggregate.adoc[Aggregate] child operator

. link:spark-sql-LogicalPlan.adoc#UnaryNode[UnaryNode] operators

`PullupCorrelatedPredicates` is part of link:spark-sql-Optimizer.adoc#Pullup-Correlated-Expressions[Pullup Correlated Expressions] once-executed batch in the standard batches of the link:spark-sql-Optimizer.adoc[Catalyst Optimizer].

Technically, `PullupCorrelatedPredicates` is a link:spark-sql-catalyst-Rule.adoc[Catalyst rule] for transforming link:spark-sql-LogicalPlan.adoc[logical plans], i.e. `Rule[LogicalPlan]`.

[source, scala]
----
import org.apache.spark.sql.catalyst.optimizer.PullupCorrelatedPredicates

// FIXME
// Demo: Filter + Aggregate
// Demo: Filter + UnaryNode

val plan = ???
val optimizedPlan = PullupCorrelatedPredicates(plan)
----

`PullupCorrelatedPredicates` uses link:spark-sql-PredicateHelper.adoc[PredicateHelper] for...FIXME

=== [[pullOutCorrelatedPredicates]] `pullOutCorrelatedPredicates` Internal Method

[source, scala]
----
pullOutCorrelatedPredicates(
  sub: LogicalPlan,
  outer: Seq[LogicalPlan]): (LogicalPlan, Seq[Expression])
----

`pullOutCorrelatedPredicates`...FIXME

NOTE: `pullOutCorrelatedPredicates` is used exclusively when `PullupCorrelatedPredicates` is requested to <<rewriteSubQueries, rewriteSubQueries>>.

=== [[rewriteSubQueries]] `rewriteSubQueries` Internal Method

[source, scala]
----
rewriteSubQueries(plan: LogicalPlan, outerPlans: Seq[LogicalPlan]): LogicalPlan
----

`rewriteSubQueries`...FIXME

NOTE: `rewriteSubQueries` is used exclusively when `PullupCorrelatedPredicates` is <<apply, executed>> (i.e. applied to a link:spark-sql-LogicalPlan.adoc[logical plan]).

=== [[apply]] Applying PullupCorrelatedPredicates To Logical Plan (Executing PullupCorrelatedPredicates) -- `apply` Method

[source, scala]
----
apply(plan: LogicalPlan): LogicalPlan
----

NOTE: `apply` is part of link:spark-sql-catalyst-Rule.adoc#apply[Rule Contract] to apply a rule to a link:spark-sql-catalyst-TreeNode.adoc[TreeNode], e.g. link:spark-sql-LogicalPlan.adoc[logical plan].

`apply` transforms the input link:spark-sql-LogicalPlan.adoc[logical plan] as follows:

. For link:spark-sql-LogicalPlan-Filter.adoc[Filter] operators with an link:spark-sql-LogicalPlan-Aggregate.adoc[Aggregate] child operator, `apply` <<rewriteSubQueries, rewriteSubQueries>> with the `Filter` and the `Aggregate` and its link:spark-sql-LogicalPlan-Aggregate.adoc#child[child] as the outer plans

. For link:spark-sql-LogicalPlan.adoc#UnaryNode[UnaryNode] operators, `apply` <<rewriteSubQueries, rewriteSubQueries>> with the operator and its children as the outer plans
