== [[SizeInBytesOnlyStatsPlanVisitor]] SizeInBytesOnlyStatsPlanVisitor

`SizeInBytesOnlyStatsPlanVisitor` is a link:spark-sql-LogicalPlanVisitor.adoc[LogicalPlanVisitor] that computes a single dimension for plan statistics, i.e. the size (in bytes).

=== [[default]] `default` Method

[source, scala]
----
default(p: LogicalPlan): Statistics
----

NOTE: `default` is a part of link:spark-sql-LogicalPlanVisitor.adoc#default[LogicalPlanVisitor Contract] to compute the size statistic (in bytes) of a logical operator.

`default` requests a link:spark-sql-LogicalPlan-LeafNode.adoc[leaf logical operator] for the statistics or creates a `Statistics` with the product of the `sizeInBytes` statistic of every link:spark-sql-catalyst-TreeNode.adoc#children[child operator].

NOTE: `default` uses the cache of the estimated statistics of a logical operator so the `Statistics` of the operator is link:spark-sql-LogicalPlanStats.adoc#stats[computed] once until it is link:spark-sql-LogicalPlanStats.adoc#invalidateStatsCache[invalidated].
