== [[Expression]] Catalyst Expression -- Executable Node in Catalyst Tree

`Expression` is a executable link:spark-sql-catalyst-TreeNode.adoc[node] (in a Catalyst tree) that can <<eval, evaluate>> a result value given input values, i.e. can produce a JVM object per `InternalRow`.

NOTE: `Expression` is often called a *Catalyst expression* even though it is _merely_ built using (not be part of) the link:spark-sql-catalyst.adoc[Catalyst -- Tree Manipulation Framework].

[source, scala]
----
// evaluating an expression
// Use Literal expression to create an expression from a Scala object
import org.apache.spark.sql.catalyst.expressions.Expression
import org.apache.spark.sql.catalyst.expressions.Literal
val e: Expression = Literal("hello")

import org.apache.spark.sql.catalyst.expressions.EmptyRow
val v: Any = e.eval(EmptyRow)

// Convert to Scala's String
import org.apache.spark.unsafe.types.UTF8String
scala> val s = v.asInstanceOf[UTF8String].toString
s: String = hello
----

`Expression` can <<genCode, generate a Java source code>> that is then used in evaluation.

[[deterministic]]
`Expression` is *deterministic* when always evaluates the same result for the same inputs. By default, an expression is deterministic if all the link:spark-sql-catalyst-TreeNode.adoc#children[child] expressions are (which for <<LeafExpression, leaf expressions>> with no child expressions is true).

NOTE: A deterministic expression is like a https://en.wikipedia.org/wiki/Pure_function[pure function] in functional programming languages.

[source, scala]
----
scala> spark.version
res0: String = 2.3.0

val e = $"a".expr
scala> :type e
org.apache.spark.sql.catalyst.expressions.Expression

scala> println(e.deterministic)
true
----

[[verboseString]]
`verboseString` is...FIXME

[[specialized-expressions]]
.Specialized Expressions
[cols="1,2,2,1",options="header",width="100%"]
|===
| Name
| Scala Kind
| Behaviour
| Examples

| [[BinaryExpression]] `BinaryExpression`
| abstract class
|
a|

* link:spark-sql-Expression-UnixTimestamp.adoc[UnixTimestamp]

| [[CodegenFallback]] link:spark-sql-Expression-CodegenFallback.adoc[CodegenFallback]
| trait
| Does not support code generation and falls back to interpreted mode
a|

* link:spark-sql-Expression-CallMethodViaReflection.adoc[CallMethodViaReflection]

| [[ExpectsInputTypes]] `ExpectsInputTypes`
| trait
|
|

| [[ExtractValue]] `ExtractValue`
| trait
| Marks `UnresolvedAliases` to be resolved to link:spark-sql-Expression-Alias.adoc[Aliases] with "pretty" SQLs when link:spark-sql-ResolveAliases.adoc#assignAliases[ResolveAliases] is executed
a|

* link:spark-sql-Expression-GetArrayItem.adoc[GetArrayItem]

* link:spark-sql-Expression-GetArrayStructFields.adoc[GetArrayStructFields]

* link:spark-sql-Expression-GetMapValue.adoc[GetMapValue]

* link:spark-sql-Expression-GetStructField.adoc[GetStructField]

| [[LeafExpression]] `LeafExpression`
| abstract class
| Has no link:spark-sql-catalyst-TreeNode.adoc#children[child expressions] (and hence "terminates" the expression tree).
a|

* link:spark-sql-Expression-Attribute.adoc[Attribute]
* link:spark-sql-Expression-Literal.adoc[Literal]

| [[NamedExpression]] link:spark-sql-Expression-NamedExpression.adoc[NamedExpression]
|
| Can later be referenced in a dataflow graph.
|

| [[Nondeterministic]] link:spark-sql-Expression-Nondeterministic.adoc[Nondeterministic]
| trait
|
|

| [[NonSQLExpression]] `NonSQLExpression`
| trait
| Expression with no SQL representation

Gives the only custom <<sql, sql>> method that is non-overridable (i.e. `final`).

When requested <<sql, SQL representation>>, `NonSQLExpression` transforms link:spark-sql-Expression-Attribute.adoc[Attributes] to be ``PrettyAttribute``s to build text representation.
a|

* link:spark-sql-Expression-ScalaUDAF.adoc[ScalaUDAF]
* link:spark-sql-Expression-StaticInvoke.adoc[StaticInvoke]
* link:spark-sql-Expression-TimeWindow.adoc[TimeWindow]

| [[Predicate]] `Predicate`
| trait
| Result link:spark-sql-Expression.adoc#dataType[data type] is always link:spark-sql-DataType.adoc#BooleanType[boolean]
a|
* `And`
* `AtLeastNNonNulls`
* link:spark-sql-Expression-Exists.adoc[Exists]
* link:spark-sql-Expression-In.adoc[In]
* link:spark-sql-Expression-InSet.adoc[InSet]

| [[TernaryExpression]] `TernaryExpression`
| abstract class
|
|

| [[TimeZoneAwareExpression]] `TimeZoneAwareExpression`
| trait
| Timezone-aware expressions
a|

* link:spark-sql-Expression-UnixTimestamp.adoc[UnixTimestamp]
* link:spark-sql-Expression-JsonToStructs.adoc[JsonToStructs]

| [[UnaryExpression]] `UnaryExpression`
| abstract class
|
a|

* link:spark-sql-Expression-Generator.adoc#ExplodeBase[ExplodeBase]
* link:spark-sql-Expression-Inline.adoc[Inline]
* link:spark-sql-Expression-JsonToStructs.adoc[JsonToStructs]

| `Unevaluable`
| trait
a| [[Unevaluable]] Cannot be evaluated, i.e. <<eval, eval>> and <<doGenCode, doGenCode>> are not supported and report an `UnsupportedOperationException`.

`Unevaluable` expressions have to be replaced by some other expressions during link:spark-sql-Analyzer.adoc[analysis] or link:spark-sql-Optimizer.adoc[optimization] or they fail analysis.

```
/**
Example: Analysis failure due to an Unevaluable expression
UnresolvedFunction is an Unevaluable expression
Using Catalyst DSL to create a UnresolvedFunction
*/
import org.apache.spark.sql.catalyst.dsl.expressions._
val f = 'f.function()

import org.apache.spark.sql.catalyst.dsl.plans._
val logicalPlan = table("t1").select(f)
scala> println(logicalPlan.numberedTreeString)
00 'Project [unresolvedalias('f(), None)]
01 +- 'UnresolvedRelation `t1`

scala> spark.sessionState.analyzer.execute(logicalPlan)
org.apache.spark.sql.AnalysisException: Undefined function: 'f'. This function is neither a registered temporary function nor a permanent function registered in the database 'default'.;
  at org.apache.spark.sql.catalyst.analysis.Analyzer$LookupFunctions$$anonfun$apply$15$$anonfun$applyOrElse$49.apply(Analyzer.scala:1198)
  at org.apache.spark.sql.catalyst.analysis.Analyzer$LookupFunctions$$anonfun$apply$15$$anonfun$applyOrElse$49.apply(Analyzer.scala:1198)
  at org.apache.spark.sql.catalyst.analysis.package$.withPosition(package.scala:48)
  at org.apache.spark.sql.catalyst.analysis.Analyzer$LookupFunctions$$anonfun$apply$15.applyOrElse(Analyzer.scala:1197)
  at org.apache.spark.sql.catalyst.analysis.Analyzer$LookupFunctions$$anonfun$apply$15.applyOrElse(Analyzer.scala:1195)
```

a|

* link:spark-sql-Expression-AggregateExpression.adoc[AggregateExpression]
* `CurrentDatabase`
* link:spark-sql-Expression-TimeWindow.adoc[TimeWindow]
* link:spark-sql-Expression-UnresolvedFunction.adoc[UnresolvedFunction]
* link:spark-sql-Expression-WindowExpression.adoc[WindowExpression]
* link:spark-sql-Expression-WindowSpecDefinition.adoc[WindowSpecDefinition]
|===

=== [[contract]] Expression Contract

[source, scala]
----
package org.apache.spark.sql.catalyst.expressions

abstract class Expression extends TreeNode[Expression] {
  // only required methods that have no implementation
  def dataType: DataType
  def doGenCode(ctx: CodegenContext, ev: ExprCode): ExprCode
  def eval(input: InternalRow = EmptyRow): Any
  def nullable: Boolean
}
----

.(Subset of) Expression Contract
[cols="1,2",options="header",width="100%"]
|===
| Method
| Description

| [[canonicalized]] `canonicalized`
|

| [[checkInputDataTypes]] `checkInputDataTypes`
|

| [[childrenResolved]] `childrenResolved`
|

| [[dataType]] `dataType`
| link:spark-sql-DataType.adoc[Data type] of the result of evaluating an expression

| [[doGenCode]] `doGenCode`
| *Code-generated expression evaluation* that generates a Java source code (that is used to evaluate the expression in a more optimized way not directly using <<eval, eval>>).

Used as part of <<genCode, genCode>>.

| [[eval]] `eval`
a| *Interpreted (non-code-generated) expression evaluation* that evaluates an expression to a JVM object for a given link:spark-sql-InternalRow.adoc[internal binary row] (without <<genCode, generating a corresponding Java code>>.)

NOTE: By default accepts `EmptyRow`, i.e. `null`.

| [[foldable]] `foldable`
|

| [[genCode]] `genCode`
| *Code-generated (non-interpreted) expression evaluation* that generates a Java source code (that is used to evaluate an expression on an input link:spark-sql-InternalRow.adoc[internal row] in a more optimized way not directly using <<eval, eval>>).

Similar to <<doGenCode, doGenCode>> but supports expression reuse (aka link:spark-sql-subexpression-elimination.adoc[subexpression elimination]).

| [[nullable]] `nullable`
|

| [[prettyName]] `prettyName`
|

| [[references]] `references`
|

| [[resolved]] `resolved`
|

| [[semanticEquals]] `semanticEquals`
|

| [[semanticHash]] `semanticHash`
|

| [[sql]] `sql`
a| SQL representation

<<prettyName, prettyName>> followed by `sql` of link:spark-sql-catalyst-TreeNode.adoc#children[children] in the round brackets and concatenated using the comma (`,`), e.g.

```
import org.apache.spark.sql.catalyst.dsl.expressions._
import org.apache.spark.sql.catalyst.expressions.Sentences
val sentences = Sentences("Hi there! Good morning.", "en", "US")

import org.apache.spark.sql.catalyst.expressions.Expression
val expr: Expression = count("*") === 5 && count(sentences) === 5
scala> expr.sql
res0: String = ((count('*') = 5) AND (count(sentences('Hi there! Good morning.', 'en', 'US')) = 5))
```
|===
