== Dataset API -- Dataset Operators

Dataset API is a <<methods, set of operators>> with typed and untyped transformations, and actions to work with a structured query (as a <<spark-sql-Dataset.adoc#, Dataset>>) as a whole.

[[methods]]
[[operators]]
.Dataset Operators (Transformations and Actions)
[cols="1,3",options="header",width="100%"]
|===
| Operator
| Description

| <<spark-sql-Dataset-typed-transformations.adoc#as, as>>
a| [[as]] Typed transformation

[source, scala]
----
as(alias: String): Dataset[T]
as(alias: Symbol): Dataset[T]
----

| <<spark-sql-Dataset-untyped-transformations.adoc#agg, agg>>
a| [[agg]] Untyped transformation

[source, scala]
----
agg(aggExpr: (String, String), aggExprs: (String, String)*): DataFrame
agg(expr: Column, exprs: Column*): DataFrame
agg(exprs: Map[String, String]): DataFrame
----

| <<spark-sql-Dataset-typed-transformations.adoc#alias, alias>>
a| [[alias]] Typed transformation

[source, scala]
----
alias(alias: String): Dataset[T]
alias(alias: Symbol): Dataset[T]
----

| <<spark-sql-Dataset-untyped-transformations.adoc#apply, apply>>
a| [[apply]] Untyped transformation to select a column based on the column name (i.e. maps a `Dataset` onto a `Column`)

[source, scala]
----
apply(colName: String): Column
----

| <<spark-sql-Dataset-typed-transformations.adoc#as-alias, as>>
a| [[as-alias]] Typed transformation

[source, scala]
----
as(alias: String): Dataset[T]
as(alias: Symbol): Dataset[T]
----

| <<spark-sql-Dataset-typed-transformations.adoc#as-type, as>>
a| [[as-type]] Typed transformation to enforce a type, i.e. marking the records in the `Dataset` as of a given data type (_data type conversion_)

[source, scala]
----
as[U : Encoder]: Dataset[U]
----

| <<spark-sql-Dataset-basic-actions.adoc#cache, cache>>
a| [[cache]] Basic action to cache a Dataset

[source, scala]
----
cache(): this.type
----

| <<spark-sql-Dataset-basic-actions.adoc#checkpoint, checkpoint>>
a| [[checkpoint]] Basic action to checkpoint a Dataset in a reliable way

[source, scala]
----
checkpoint(): Dataset[T]
checkpoint(eager: Boolean): Dataset[T]
----

| <<spark-sql-Dataset-typed-transformations.adoc#coalesce, coalesce>>
a| [[coalesce]] Typed transformation to repartition a Dataset

[source, scala]
----
coalesce(numPartitions: Int): Dataset[T]
----

| <<spark-sql-Dataset-untyped-transformations.adoc#col, col>>
a| [[col]] Untyped transformation to select a column based on the column name (i.e. maps a `Dataset` onto a `Column`)

[source, scala]
----
col(colName: String): Column
----

| <<spark-sql-Dataset-actions.adoc#collect, collect>>
| [[collect]] Action

| <<spark-sql-Dataset-untyped-transformations.adoc#colRegex, colRegex>>
a| [[colRegex]] (*New in 2.3.0*) Untyped transformation to select a column based on the column name specified as a regex (i.e. maps a `Dataset` onto a `Column`)

[source, scala]
----
colRegex(colName: String): Column
----

| <<spark-sql-Dataset-basic-actions.adoc#columns, columns>>
a| [[columns]] Basic action

[source, scala]
----
columns: Array[String]
----

| <<spark-sql-Dataset-actions.adoc#count, count>>
a| [[count]] Action to count the number of rows

[source, scala]
----
count(): Long
----

| <<spark-sql-Dataset-basic-actions.adoc#createGlobalTempView, createGlobalTempView>>
a| [[createGlobalTempView]] Basic action

[source, scala]
----
createGlobalTempView(viewName: String): Unit
----

| <<spark-sql-Dataset-basic-actions.adoc#createOrReplaceGlobalTempView, createOrReplaceGlobalTempView>>
a| [[createOrReplaceGlobalTempView]] Basic action

[source, scala]
----
createOrReplaceGlobalTempView(viewName: String): Unit
----

| <<spark-sql-Dataset-basic-actions.adoc#createOrReplaceTempView, createOrReplaceTempView>>
a| [[createOrReplaceTempView]] Basic action

[source, scala]
----
createOrReplaceTempView(viewName: String): Unit
----

| <<spark-sql-Dataset-basic-actions.adoc#createTempView, createTempView>>
a| [[createTempView]] Basic action

[source, scala]
----
createTempView(viewName: String): Unit
----

| <<spark-sql-Dataset-untyped-transformations.adoc#crossJoin, crossJoin>>
a| [[crossJoin]] Untyped transformation

[source, scala]
----
crossJoin(right: Dataset[_]): DataFrame
----

| <<spark-sql-Dataset-untyped-transformations.adoc#cube, cube>>
a| [[cube]] Untyped transformation

[source, scala]
----
cube(cols: Column*): RelationalGroupedDataset
cube(col1: String, cols: String*): RelationalGroupedDataset
----

| <<spark-sql-Dataset-actions.adoc#describe, describe>>
a| [[describe]] Action

[source, scala]
----
describe(cols: String*): DataFrame
----

| <<spark-sql-Dataset-typed-transformations.adoc#distinct, distinct>>
a| [[distinct]] Typed transformation

[source, scala]
----
distinct(): Dataset[T]
----

| <<spark-sql-Dataset-untyped-transformations.adoc#drop, drop>>
a| [[drop]] Untyped transformation

[source, scala]
----
drop(colName: String): DataFrame
drop(colNames: String*): DataFrame
drop(col: Column): DataFrame
----

| <<spark-sql-Dataset-typed-transformations.adoc#dropDuplicates, dropDuplicates>>
a| [[dropDuplicates]] Typed transformation

[source, scala]
----
dropDuplicates(): Dataset[T]
dropDuplicates(colNames: Array[String]): Dataset[T]
dropDuplicates(colNames: Seq[String]): Dataset[T]
dropDuplicates(col1: String, cols: String*): Dataset[T]
----

| <<spark-sql-Dataset-basic-actions.adoc#dtypes, dtypes>>
a| [[dtypes]] Basic action

[source, scala]
----
dtypes: Array[(String, String)]
----

| <<spark-sql-Dataset-typed-transformations.adoc#except, except>>
a| [[except]] Typed transformation

[source, scala]
----
except(other: Dataset[T]): Dataset[T]
----

| <<spark-sql-Dataset-basic-actions.adoc#explain, explain>>
a| [[explain]] Basic action to explain the logical and physical plans of the `Dataset`, i.e. displays the logical and physical plans (with optional cost and codegen summaries) to the standard output

[source, scala]
----
explain(): Unit
explain(extended: Boolean): Unit
----

| <<spark-sql-Dataset-typed-transformations.adoc#filter, filter>>
a| [[filter]] Typed transformation

[source, scala]
----
filter(condition: Column): Dataset[T]
filter(conditionExpr: String): Dataset[T]
filter(func: T => Boolean): Dataset[T]
----

| <<spark-sql-Dataset-actions.adoc#first, first>>
a| [[first]] Action

[source, scala]
----
first(): T
----

| <<spark-sql-Dataset-typed-transformations.adoc#flatMap, flatMap>>
a| [[flatMap]] Typed transformation

[source, scala]
----
flatMap[U : Encoder](func: T => TraversableOnce[U]): Dataset[U]
----

| <<spark-sql-Dataset-actions.adoc#foreach, foreach>>
a| [[foreach]] Action

[source, scala]
----
foreach(f: T => Unit): Unit
----

| <<spark-sql-Dataset-actions.adoc#foreachPartition, foreachPartition>>
a| [[foreachPartition]] Action

[source, scala]
----
foreachPartition(f: Iterator[T] => Unit): Unit
----

| <<spark-sql-Dataset-untyped-transformations.adoc#groupBy, groupBy>>
a| [[groupBy]] Untyped transformation

[source, scala]
----
groupBy(cols: Column*): RelationalGroupedDataset
groupBy(col1: String, cols: String*): RelationalGroupedDataset
----

| <<spark-sql-Dataset-typed-transformations.adoc#groupByKey, groupByKey>>
a| [[groupByKey]] Typed transformation

[source, scala]
----
groupByKey[K: Encoder](func: T => K): KeyValueGroupedDataset[K, T]
----

| <<spark-sql-Dataset-actions.adoc#head, head>>
a| [[head]] Action

[source, scala]
----
head(): T
head(n: Int): Array[T]
----

| <<spark-sql-Dataset-basic-actions.adoc#hint, hint>>
a| [[hint]] Basic action to specify a hint (and optional parameters)

[source, scala]
----
hint(name: String, parameters: Any*): Dataset[T]
----

| <<spark-sql-Dataset-basic-actions.adoc#inputFiles, inputFiles>>
a| [[inputFiles]] Basic action

[source, scala]
----
inputFiles: Array[String]
----

| <<spark-sql-Dataset-typed-transformations.adoc#intersect, intersect>>
a| [[intersect]] Typed transformation

[source, scala]
----
intersect(other: Dataset[T]): Dataset[T]
----

| <<spark-sql-Dataset-basic-actions.adoc#isLocal, isLocal>>
a| [[isLocal]] Basic action

[source, scala]
----
isLocal: Boolean
----

| <<spark-sql-Dataset-untyped-transformations.adoc#join, join>>
a| [[join]] Untyped transformation

[source, scala]
----
join(right: Dataset[_]): DataFrame
join(right: Dataset[_], usingColumn: String): DataFrame
join(right: Dataset[_], usingColumns: Seq[String]): DataFrame
join(right: Dataset[_], usingColumns: Seq[String], joinType: String): DataFrame
join(right: Dataset[_], joinExprs: Column): DataFrame
join(right: Dataset[_], joinExprs: Column, joinType: String): DataFrame
----

| <<spark-sql-Dataset-typed-transformations.adoc#joinWith, joinWith>>
a| [[joinWith]] Typed transformation

[source, scala]
----
joinWith[U](other: Dataset[U], condition: Column): Dataset[(T, U)]
joinWith[U](other: Dataset[U], condition: Column, joinType: String): Dataset[(T, U)]
----

| <<spark-sql-Dataset-typed-transformations.adoc#limit, limit>>
a| [[limit]] Typed transformation

[source, scala]
----
limit(n: Int): Dataset[T]
----

| <<spark-sql-Dataset-basic-actions.adoc#localCheckpoint, localCheckpoint>>
a| [[localCheckpoint]] (*New in 2.3.0*) Basic action to checkpoint the Dataset locally on executors (and therefore unreliably)

[source, scala]
----
localCheckpoint(): Dataset[T]
localCheckpoint(eager: Boolean): Dataset[T]
----

| <<spark-sql-Dataset-typed-transformations.adoc#map, map>>
a| [[map]] Typed transformation

[source, scala]
----
map[U: Encoder](func: T => U): Dataset[U]
----

| <<spark-sql-Dataset-typed-transformations.adoc#mapPartitions, mapPartitions>>
a| [[mapPartitions]] Typed transformation

[source, scala]
----
mapPartitions[U : Encoder](func: Iterator[T] => Iterator[U]): Dataset[U]
----

| <<spark-sql-Dataset-untyped-transformations.adoc#na, na>>
a| [[na]] Untyped transformation

[source, scala]
----
na: DataFrameNaFunctions
----

| <<spark-sql-Dataset-typed-transformations.adoc#orderBy, orderBy>>
a| [[orderBy]] Typed transformation

[source, scala]
----
orderBy(sortExprs: Column*): Dataset[T]
orderBy(sortCol: String, sortCols: String*): Dataset[T]
----

| <<spark-sql-Dataset-basic-actions.adoc#persist, persist>>
a| [[persist]] Basic action to persist a Dataset

[source, scala]
----
persist(): this.type
persist(newLevel: StorageLevel): this.type
----

| <<spark-sql-Dataset-basic-actions.adoc#printSchema, printSchema>>
a| [[printSchema]] Basic action

[source, scala]
----
printSchema(): Unit
----

| <<spark-sql-Dataset-typed-transformations.adoc#randomSplit, randomSplit>>
a| [[randomSplit]] Typed transformation to split a Dataset randomly into two Datasets

[source, scala]
----
randomSplit(weights: Array[Double]): Array[Dataset[T]]
randomSplit(weights: Array[Double], seed: Long): Array[Dataset[T]]
----

| <<spark-sql-Dataset-basic-actions.adoc#rdd, rdd>>
a| [[rdd]] Basic action

[source, scala]
----
rdd: RDD[T]
----

| <<spark-sql-Dataset-actions.adoc#reduce, reduce>>
a| [[reduce]] Action to reduce the records of the `Dataset` using the specified binary function.

[source, scala]
----
reduce(func: (T, T) => T): T
----

| <<spark-sql-Dataset-typed-transformations.adoc#repartition, repartition>>
a| [[repartition]] Typed transformation to repartition a Dataset

[source, scala]
----
repartition(partitionExprs: Column*): Dataset[T]
repartition(numPartitions: Int): Dataset[T]
repartition(numPartitions: Int, partitionExprs: Column*): Dataset[T]
----

| <<spark-sql-Dataset-typed-transformations.adoc#repartitionByRange, repartitionByRange>>
a| [[repartitionByRange]] (*New in 2.3.0*) Typed transformation

[source, scala]
----
repartitionByRange(partitionExprs: Column*): Dataset[T]
repartitionByRange(numPartitions: Int, partitionExprs: Column*): Dataset[T]
----

| <<spark-sql-Dataset-untyped-transformations.adoc#rollup, rollup>>
a| [[rollup]] Untyped transformation

[source, scala]
----
rollup(cols: Column*): RelationalGroupedDataset
rollup(col1: String, cols: String*): RelationalGroupedDataset
----

| <<spark-sql-Dataset-typed-transformations.adoc#sample, sample>>
a| [[sample]] Typed transformation

[source, scala]
----
sample(withReplacement: Boolean, fraction: Double): Dataset[T]
sample(withReplacement: Boolean, fraction: Double, seed: Long): Dataset[T]
sample(fraction: Double): Dataset[T]  // <1>
sample(fraction: Double, seed: Long): Dataset[T]  // <2>
----
<1> *New in 2.3.0*
<2> *New in 2.3.0*

| <<spark-sql-Dataset-basic-actions.adoc#schema, schema>>
a| [[schema]] Basic action

[source, scala]
----
schema: StructType
----

| <<spark-sql-Dataset-untyped-transformations.adoc#select, select>>
a| [[select]] Transformation

[source, scala]
----
// Untyped transformations
select(cols: Column*): DataFrame
select(col: String, cols: String*): DataFrame

// Typed transformations
select[U1](c1: TypedColumn[T, U1]): Dataset[U1]
select[U1, U2](c1: TypedColumn[T, U1], c2: TypedColumn[T, U2]): Dataset[(U1, U2)]
select[U1, U2, U3](
  c1: TypedColumn[T, U1],
  c2: TypedColumn[T, U2],
  c3: TypedColumn[T, U3]): Dataset[(U1, U2, U3)]
select[U1, U2, U3, U4](
  c1: TypedColumn[T, U1],
  c2: TypedColumn[T, U2],
  c3: TypedColumn[T, U3],
  c4: TypedColumn[T, U4]): Dataset[(U1, U2, U3, U4)]
select[U1, U2, U3, U4, U5](
  c1: TypedColumn[T, U1],
  c2: TypedColumn[T, U2],
  c3: TypedColumn[T, U3],
  c4: TypedColumn[T, U4],
  c5: TypedColumn[T, U5]): Dataset[(U1, U2, U3, U4, U5)]
----

| <<spark-sql-Dataset-untyped-transformations.adoc#selectExpr, selectExpr>>
a| [[selectExpr]] Untyped transformation

[source, scala]
----
selectExpr(exprs: String*): DataFrame
----

| <<spark-sql-Dataset-actions.adoc#show, show>>
a| [[show]] Action

[source, scala]
----
show(): Unit
show(truncate: Boolean): Unit
show(numRows: Int): Unit
show(numRows: Int, truncate: Boolean): Unit
show(numRows: Int, truncate: Int): Unit
show(numRows: Int, truncate: Int, vertical: Boolean): Unit // <1>
----
<1> *New in 2.3.0*

| <<spark-sql-Dataset-typed-transformations.adoc#sort, sort>>
a| [[sort]] Typed transformation

[source, scala]
----
sort(sortExprs: Column*): Dataset[T]
sort(sortCol: String, sortCols: String*): Dataset[T]
----

| <<spark-sql-Dataset-typed-transformations.adoc#sortWithinPartitions, sortWithinPartitions>>
a| [[sortWithinPartitions]] Typed transformation

[source, scala]
----
sortWithinPartitions(sortExprs: Column*): Dataset[T]
sortWithinPartitions(sortCol: String, sortCols: String*): Dataset[T]
----

| <<spark-sql-Dataset-untyped-transformations.adoc#stat, stat>>
a| [[stat]] Untyped transformation

[source, scala]
----
stat: DataFrameStatFunctions
----

| <<spark-sql-Dataset-basic-actions.adoc#storageLevel, storageLevel>>
a| [[storageLevel]] Basic action

[source, scala]
----
storageLevel: StorageLevel
----

| <<spark-sql-Dataset-actions.adoc#summary, summary>>
a| [[summary]] (*New in 2.3.0*) Action to calculate statistics (e.g. `count`, `mean`, `stddev`, `min`, `max` and `25%`, `50%`, `75%` percentiles)

[source, scala]
----
summary(statistics: String*): DataFrame
----

| <<spark-sql-Dataset-actions.adoc#take, take>>
a| [[take]] Action to take the first records of a Dataset

[source, scala]
----
take(n: Int): Array[T]
----

| <<spark-sql-Dataset-basic-actions.adoc#toDF, toDF>>
a| [[toDF]] Basic action to convert a Dataset to a DataFrame

[source, scala]
----
toDF(): DataFrame
toDF(colNames: String*): DataFrame
----

| <<spark-sql-Dataset-typed-transformations.adoc#toJSON, toJSON>>
a| [[toJSON]] Typed transformation

[source, scala]
----
toJSON: Dataset[String]
----

| <<spark-sql-Dataset-actions.adoc#toLocalIterator, toLocalIterator>>
a| [[toLocalIterator]] Action

[source, scala]
----
toLocalIterator(): java.util.Iterator[T]
----

| <<spark-sql-Dataset-typed-transformations.adoc#transform, transform>>
a| [[transform]] Typed transformation for chaining custom transformations

[source, scala]
----
transform[U](t: Dataset[T] => Dataset[U]): Dataset[U]
----

| <<spark-sql-Dataset-typed-transformations.adoc#union, union>>
a| [[union]] Typed transformation

[source, scala]
----
union(other: Dataset[T]): Dataset[T]
----

| <<spark-sql-Dataset-typed-transformations.adoc#unionByName, unionByName>>
a| [[unionByName]] (*New in 2.3.0*) Typed transformation

[source, scala]
----
unionByName(other: Dataset[T]): Dataset[T]
----

| <<spark-sql-Dataset-basic-actions.adoc#unpersist, unpersist>>
a| [[unpersist]] Basic action to unpersist a cached Dataset

[source, scala]
----
unpersist(): this.type
unpersist(blocking: Boolean): this.type
----

| <<spark-sql-Dataset-typed-transformations.adoc#where, where>>
a| [[where]] Typed transformation

[source, scala]
----
where(condition: Column): Dataset[T]
where(conditionExpr: String): Dataset[T]
----

| <<spark-sql-Dataset-untyped-transformations.adoc#withColumn, withColumn>>
a| [[withColumn]] Untyped transformation

[source, scala]
----
withColumn(colName: String, col: Column): DataFrame
----

| <<spark-sql-Dataset-untyped-transformations.adoc#withColumnRenamed, withColumnRenamed>>
a| [[withColumnRenamed]] Untyped transformation

[source, scala]
----
withColumnRenamed(existingName: String, newName: String): DataFrame
----

| <<spark-sql-Dataset-basic-actions.adoc#write, write>>
a| [[write]] Basic action to return a <<spark-sql-DataFrameWriter.adoc#, DataFrameWriter>>

[source, scala]
----
write: DataFrameWriter[T]
----
|===
