== [[HiveClient]] HiveClient -- Contract for Retrieving Metadata from Hive Metastore

`HiveClient` is the <<contract, contract>> for...FIXME

NOTE: link:spark-sql-HiveClientImpl.adoc[HiveClientImpl] is the only available `HiveClient` in Spark SQL.

`HiveClient` offers _safe_ variants of many methods that do not report exceptions when a relational entity is not found in a Hive metastore, e.g. <<getTableOption, getTableOption>> for <<getTable, getTable>>.

[[contract]]
[source, scala]
----
package org.apache.spark.sql.hive.client

trait HiveClient {
  // only required methods that have no implementation
  // FIXME List of the methods
  def alterPartitions(
      db: String,
      table: String,
      newParts: Seq[CatalogTablePartition]): Unit
  def getTableOption(dbName: String, tableName: String): Option[CatalogTable]
  def getPartitions(
      catalogTable: CatalogTable,
      partialSpec: Option[TablePartitionSpec] = None): Seq[CatalogTablePartition]
  def getPartitionsByFilter(
      catalogTable: CatalogTable,
      predicates: Seq[Expression]): Seq[CatalogTablePartition]
  def getPartitionOption(
      table: CatalogTable,
      spec: TablePartitionSpec): Option[CatalogTablePartition]
  def renamePartitions(
      db: String,
      table: String,
      specs: Seq[TablePartitionSpec],
      newSpecs: Seq[TablePartitionSpec]): Unit
}
----

NOTE: `HiveClient` is a `private[hive]` contract.

.(Subset of) HiveClient Contract
[cols="1m,2",options="header",width="100%"]
|===
| Method
| Description

| alterPartitions
| [[alterPartitions]]

| `getPartitions`
a| [[getPartitions]]

[source, scala]
----
getPartitions(
  db: String,
  table: String,
  partialSpec: Option[TablePartitionSpec]): Seq[CatalogTablePartition]
getPartitions(
  catalogTable: CatalogTable,
  partialSpec: Option[TablePartitionSpec] = None): Seq[CatalogTablePartition]
----

Returns the <<spark-sql-CatalogTablePartition.adoc#, CatalogTablePartition>> of a table

Used exclusively when `HiveExternalCatalog` is requested to <<spark-sql-HiveExternalCatalog.adoc#listPartitions, list the partitions of a table>>.

| getPartitionsByFilter
| [[getPartitionsByFilter]] Used when...FIXME

| getPartitionOption
| [[getPartitionOption]] Used when...FIXME

| getTableOption
a| [[getTableOption]]

[source, scala]
----
getTableOption(dbName: String, tableName: String): Option[CatalogTable]
----

Retrieves a table metadata if available

Used exclusively when `HiveClient` is requested for a <<getTable, table metadata>>

NOTE: `getTableOption` is a safe version of <<getTable, getTable>> as it does not throw a `NoSuchTableException`, but simply returns `None`.

| renamePartitions
| [[renamePartitions]] Used when...FIXME
|===

=== [[getTable]] Retrieving Table Metadata If Available or Throwing NoSuchTableException -- `getTable` Method

[source, scala]
----
getTable(dbName: String, tableName: String): CatalogTable
----

`getTable` <<getTableOption, retrieves the metadata of a table in a Hive metastore>> if available or reports a `NoSuchTableException`.

[NOTE]
====
`getTable` is used when:

* `HiveExternalCatalog` is requested for a link:spark-sql-HiveExternalCatalog.adoc#getRawTable[table metadata]

* `HiveClient` is requested for <<getPartitionOption, getPartitionOption>> or <<getPartitions, getPartitions>>

* `HiveClientImpl` is requested for link:spark-sql-HiveClientImpl.adoc#renamePartitions[renamePartitions] or link:spark-sql-HiveClientImpl.adoc#alterPartitions[alterPartitions]
====
