== [[ReplaceExpressions]] ReplaceExpressions Logical Optimization

`ReplaceExpressions` is a *logical optimization* that <<apply, replaces RuntimeReplaceable expressions with their single child>>.

Technically, `ReplaceExpressions` is a link:spark-sql-catalyst-Rule.adoc[Catalyst rule] for transforming link:spark-sql-LogicalPlan.adoc[logical plans], i.e. `Rule[LogicalPlan]`.

[source, scala]
----
val query = sql("select ifnull(NULL, array('2')) from values 1")
val analyzedPlan = query.queryExecution.analyzed
scala> println(analyzedPlan.numberedTreeString)
00 Project [ifnull(null, array(2)) AS ifnull(NULL, array('2'))#3]
01 +- LocalRelation [col1#2]

import org.apache.spark.sql.catalyst.optimizer.ReplaceExpressions
val optimizedPlan = ReplaceExpressions(analyzedPlan)
scala> println(optimizedPlan.numberedTreeString)
00 Project [coalesce(cast(null as array<string>), cast(array(2) as array<string>)) AS ifnull(NULL, array('2'))#3]
01 +- LocalRelation [col1#2]
----

`ReplaceExpressions` is part of the link:spark-sql-Optimizer.adoc#Finish_Analysis[Finish Analysis] once-executed batch of link:spark-sql-Optimizer.adoc[Catalyst Optimizer].

=== [[apply]] Applying ReplaceExpressions Rule To Logical Plan (Executing ReplaceExpressions) -- `apply` Method

[source, scala]
----
apply(plan: LogicalPlan): LogicalPlan
----

NOTE: `apply` is part of link:spark-sql-catalyst-Rule.adoc#apply[Rule Contract] to apply a rule to a link:spark-sql-catalyst-TreeNode.adoc[TreeNode], e.g. link:spark-sql-LogicalPlan.adoc[logical plan].

`apply` link:spark-sql-catalyst-QueryPlan.adoc#transformAllExpressions[traverses all Catalyst expressions] in the input link:spark-sql-LogicalPlan.adoc[logical plan] and replaces a link:spark-sql-Expression-RuntimeReplaceable.adoc[RuntimeReplaceable] expression into its single child.
