== [[GenerateUnsafeProjection]] GenerateUnsafeProjection

`GenerateUnsafeProjection` is a link:spark-sql-CodeGenerator.adoc[CodeGenerator] for converting link:spark-sql-Expression.adoc[Catalyst expressions] to link:spark-sql-UnsafeProjection.adoc[UnsafeProjection] (i.e. `CodeGenerator[Seq[Expression], UnsafeProjection]`).

[source, scala]
----
GenerateUnsafeProjection: Seq[Expression] => UnsafeProjection
----

[TIP]
====
Enable `DEBUG` logging level for `org.apache.spark.sql.catalyst.expressions.codegen.GenerateUnsafeProjection` logger to see what happens inside.

Add the following line to `conf/log4j.properties`:

```
log4j.logger.org.apache.spark.sql.catalyst.expressions.codegen.GenerateUnsafeProjection=DEBUG
```

Refer to link:spark-logging.adoc[Logging].
====

=== [[generate]] Generating UnsafeProjection -- `generate` Method

[source, scala]
----
generate(
  expressions: Seq[Expression],
  subexpressionEliminationEnabled: Boolean): UnsafeProjection
----

`generate` <<create, creates a UnsafeProjection>> with `expressions` <<canonicalize, canonicalized>>.

NOTE: `generate` is used when `UnsafeProjection` factory object is requested for a link:spark-sql-UnsafeProjection.adoc#create[UnsafeProjection].

=== [[canonicalize]] `canonicalize` Method

[source, scala]
----
canonicalize(in: Seq[Expression]): Seq[Expression]
----

`canonicalize` removes unnecessary `Alias` expressions.

Internally, `canonicalize` uses `ExpressionCanonicalizer` rule executor (that in turn uses just one `CleanExpressions` expression rule).

=== [[create]] Creating UnsafeProjection -- `create` Method

[source, scala]
----
create(
  expressions: Seq[Expression],
  subexpressionEliminationEnabled: Boolean): UnsafeProjection
create(references: Seq[Expression]): UnsafeProjection // <1>
----
<1> Calls the former `create` with `subexpressionEliminationEnabled` flag off

`create` first creates a link:spark-sql-CodeGenerator.adoc#newCodeGenContext[CodegenContext] and an <<createCode, ExprCode>> for the input `expressions` that is converted to a Java source code (as `CodeAndComment`).

You should see the following DEBUG message in the logs:

```
DEBUG GenerateUnsafeProjection: code for [expressions]:
[code]
```

[TIP]
====
Enable `DEBUG` logging level for `org.apache.spark.sql.catalyst.expressions.codegen.CodeGenerator` logger to see the message above.

```
log4j.logger.org.apache.spark.sql.catalyst.expressions.codegen.CodeGenerator=DEBUG
```

See link:spark-sql-CodeGenerator.adoc#logging[CodeGenerator].
====

`create` requests `CodeGenerator` to link:spark-sql-CodeGenerator.adoc#compile[compile the Java source code into a GeneratedClass].

You should see the following INFO message in the logs:

```
INFO CodeGenerator: Code generated in [time] ms
```

[TIP]
====
Enable `INFO` logging level for `org.apache.spark.sql.catalyst.expressions.codegen.CodeGenerator` logger to see the message above.

```
log4j.logger.org.apache.spark.sql.catalyst.expressions.codegen.CodeGenerator=INFO
```

See link:spark-sql-CodeGenerator.adoc#logging[CodeGenerator].
====

`create` passes references into the `GeneratedClass` that eventually becomes the final link:spark-sql-UnsafeProjection.adoc[UnsafeProjection].

NOTE: (Single-argument) `create` is a part of link:spark-sql-CodeGenerator.adoc#create[CodeGenerator Contract].

=== [[createCode]] Creating ExprCode for Catalyst Expressions -- `createCode` Method

[source, scala]
----
createCode(
  ctx: CodegenContext,
  expressions: Seq[Expression],
  useSubexprElimination: Boolean = false): ExprCode
----

`createCode` requests the input `CodegenContext` to link:spark-sql-CodegenContext.adoc#generateExpressions[generateExpressions].

`createCode`...FIXME

[source, scala]
----
import org.apache.spark.sql.catalyst.expressions.codegen.CodegenContext
val ctx = new CodegenContext

// Use Catalyst DSL
import org.apache.spark.sql.catalyst.dsl.expressions._
val expressions = "hello".expr.as("world") :: "hello".expr.as("world") :: Nil

import org.apache.spark.sql.catalyst.expressions.codegen.GenerateUnsafeProjection
val eval = GenerateUnsafeProjection.createCode(ctx, expressions, useSubexprElimination = true)

scala> println(eval.code)

        mutableStateArray1[0].reset();

        mutableStateArray2[0].write(0, ((UTF8String) references[0] /* literal */));


            mutableStateArray2[0].write(1, ((UTF8String) references[1] /* literal */));
        mutableStateArray[0].setTotalSize(mutableStateArray1[0].totalSize());


scala> println(eval.value)
mutableStateArray[0]
----

[NOTE]
====
`createCode` is used when:

* `CreateNamedStructUnsafe` is requested to link:spark-sql-Expression-CreateNamedStructUnsafe.adoc#doGenCode[generate a Java source code]

* `GenerateUnsafeProjection` is requested to <<create, create a UnsafeProjection>>

* `CodegenSupport` is requested to link:spark-sql-CodegenSupport.adoc#prepareRowVar[prepareRowVar] (to link:spark-sql-CodegenSupport.adoc#consume[generate a Java source code to consume generated columns or row from a physical operator])

* `HashAggregateExec` is requested to link:spark-sql-SparkPlan-HashAggregateExec.adoc#doProduceWithKeys[doProduceWithKeys] and link:spark-sql-SparkPlan-HashAggregateExec.adoc#doConsumeWithKeys[doConsumeWithKeys]

* `BroadcastHashJoinExec` is requested to link:spark-sql-SparkPlan-BroadcastHashJoinExec.adoc#genStreamSideJoinKey[genStreamSideJoinKey] (when generating the Java source code for joins)
====
