== [[OrderedDistribution]] OrderedDistribution

`OrderedDistribution` is a link:spark-sql-Distribution.adoc[Distribution] that...FIXME

[[requiredNumPartitions]]
`OrderedDistribution` specifies `None` for the link:spark-sql-Distribution.adoc#requiredNumPartitions[required number of partitions].

CAUTION: FIXME What does `None` mean?

`OrderedDistribution` is <<creating-instance, created>> when...FIXME

[[creating-instance]]
[[ordering]]
`OrderedDistribution` takes `SortOrder` expressions for ordering when created.

`OrderedDistribution` requires that the <<ordering, ordering expressions>> should not be empty (i.e. `Nil`).

=== [[createPartitioning]] `createPartitioning` Method

[source, scala]
----
createPartitioning(numPartitions: Int): Partitioning
----

NOTE: `createPartitioning` is part of link:spark-sql-Distribution.adoc#createPartitioning[Distribution Contract] to create a link:spark-sql-SparkPlan-Partitioning.adoc[Partitioning] for a given number of partitions.

`createPartitioning`...FIXME
