== [[FileFormat]] FileFormat

`FileFormat` is the <<contract, contract>> in Spark SQL to <<buildReader, read>> and <<prepareWrite, write>> data stored in files (to/from the link:spark-sql-InternalRow.adoc[InternalRow] format).

[[contract]]
[source, scala]
----
package org.apache.spark.sql.execution.datasources

trait FileFormat {
  // only required methods that have no implementation
  // the others follow
  def inferSchema(
    sparkSession: SparkSession,
    options: Map[String, String],
    files: Seq[FileStatus]): Option[StructType]
  def prepareWrite(
    sparkSession: SparkSession,
    job: Job,
    options: Map[String, String],
    dataSchema: StructType): OutputWriterFactory
}
----

.(Subset of) FileFormat Contract
[cols="1,2",options="header",width="100%"]
|===
| Method
| Description

| [[inferSchema]] `inferSchema`
| Used when...

| [[prepareWrite]] `prepareWrite`
| Used exclusively when `FileFormatWriter` is requested to link:spark-sql-FileFormatWriter.adoc#write[write the result of a structured query].
|===

[[supportBatch]]
`supportBatch`...FIXME

[[vectorTypes]]
`vectorTypes`...FIXME

[[isSplitable]]
`isSplitable`...FIXME

=== [[buildReaderWithPartitionValues]] `buildReaderWithPartitionValues` Method

[source, scala]
----
buildReaderWithPartitionValues(
  sparkSession: SparkSession,
  dataSchema: StructType,
  partitionSchema: StructType,
  requiredSchema: StructType,
  filters: Seq[Filter],
  options: Map[String, String],
  hadoopConf: Configuration): PartitionedFile => Iterator[InternalRow]
----

`buildReaderWithPartitionValues`...FIXME

NOTE: `buildReaderWithPartitionValues` is used exclusively when `FileSourceScanExec` is requested for link:spark-sql-SparkPlan-FileSourceScanExec.adoc#inputRDDs[input RDDs].

=== [[buildReader]] `buildReader` Method

[source, scala]
----
buildReader(
  sparkSession: SparkSession,
  dataSchema: StructType,
  partitionSchema: StructType,
  requiredSchema: StructType,
  filters: Seq[Filter],
  options: Map[String, String],
  hadoopConf: Configuration): PartitionedFile => Iterator[InternalRow]
----

`buildReader`...FIXME

NOTE: `buildReader` is used exclusively when `FileFormat` is requested to <<buildReaderWithPartitionValues, buildReaderWithPartitionValues>>
