== [[ColumnStat]] ColumnStat -- Column Statistics

[[creating-instance]]
`ColumnStat` represents the statistics of a column.

* [[distinctCount]] `distinctCount` metric
* [[min]] Minimum value (optional)
* [[max]] Maximum value (optional)
* [[nullCount]] `nullCount` metric
* [[avgLen]] Average length
* [[maxLen]] Maximum length
* [[histogram]] Optional histogram of values (as `Histogram` which is empty by default)

[TIP]
====
Use link:spark-sql-cost-based-optimization.adoc#ANALYZE-TABLE[ANALYZE TABLE&hellip;FOR COLUMNS] SQL command to compute column statistics.

```
val cols = "id, p1, p2"
val analyzeTableSQL = s"ANALYZE TABLE t1 COMPUTE STATISTICS FOR COLUMNS $cols"
spark.sql(analyzeTableSQL)
```

---

Use link:spark-sql-cost-based-optimization.adoc#DESCRIBE-EXTENDED[DESCRIBE EXTENDED] SQL command to list the column statistics.

```
scala> sql("DESC EXTENDED t1 id").show
+--------------+----------+
|info_name     |info_value|
+--------------+----------+
|col_name      |id        |
|data_type     |int       |
|comment       |NULL      |
|min           |0         |
|max           |1         |
|num_nulls     |0         |
|distinct_count|2         |
|avg_col_len   |4         |
|max_col_len   |4         |
|histogram     |NULL      |
+--------------+----------+
```
====

`ColumnStat` is <<creating-instance, created>> when...FIXME

[source, scala]
----
scala> spark.version
res0: String = 2.4.0-SNAPSHOT

val tableName = "t1"

// Make the example reproducible
import org.apache.spark.sql.catalyst.TableIdentifier
val tid = TableIdentifier(tableName)
val sessionCatalog = spark.sessionState.catalog
sessionCatalog.dropTable(tid, ignoreIfNotExists = true, purge = true)

// CREATE TABLE t1
Seq((0, 0, "zero"), (1, 1, "one")).
  toDF("id", "p1", "p2").
  write.
  saveAsTable("t1")

// As we drop and create immediately we may face problems with unavailable partition files
// Invalidate cache
spark.sql(s"REFRESH TABLE $tableName")

// Use ANALYZE TABLE...FOR COLUMNS to compute column statistics
// that saves them in a metastore (aka an external catalog)
val df = spark.table(tableName)
val allCols = df.columns.mkString(",")
val analyzeTableSQL = s"ANALYZE TABLE t1 COMPUTE STATISTICS FOR COLUMNS $allCols"
spark.sql(analyzeTableSQL)

// Fetch the table metadata (with column statistics) from a metastore
val metastore = spark.sharedState.externalCatalog
val db = spark.catalog.currentDatabase
val tableMeta = metastore.getTable(db, table = tableName)

// The column statistics are part of the table statistics
val colStats = tableMeta.stats.get.colStats

scala> :type colStats
Map[String,org.apache.spark.sql.catalyst.plans.logical.ColumnStat]

scala> colStats.map { case (name, cs) => s"$name: $cs" }.foreach(println)
// the output may vary
id: ColumnStat(2,Some(0),Some(1),0,4,4,None)
p1: ColumnStat(2,Some(0),Some(1),0,4,4,None)
p2: ColumnStat(2,None,None,0,4,4,None)
----

NOTE: `ColumnStat` does not support <<min, minimum>> and <<max, maximum>> metrics for binary (i.e. `Array[Byte]`) and string types.

=== [[toMap]] `toMap` Method

[source, scala]
----
toMap(colName: String, dataType: DataType): Map[String, String]
----

`toMap`...FIXME

NOTE: `toMap` is used when...FIXME

=== [[fromMap]] Creating ColumnStat from Column Statistics Properties (aka ColumnStat Deserialization) -- `fromMap` Method

[source, scala]
----
fromMap(table: String, field: StructField, map: Map[String, String]): Option[ColumnStat]
----

`fromMap`...FIXME

NOTE: `fromMap` is used exclusively when `HiveExternalCatalog` is requested for link:spark-sql-HiveExternalCatalog.adoc#statsFromProperties[restoring Spark statistics from properties] (from a Hive Metastore).

=== [[toExternalString]] `toExternalString` Internal Method

[source, scala]
----
toExternalString(v: Any, colName: String, dataType: DataType): String
----

`toExternalString`...FIXME

NOTE: `toExternalString` is used when...FIXME

=== [[rowToColumnStat]] `rowToColumnStat` Method

[source, scala]
----
rowToColumnStat(
  row: InternalRow,
  attr: Attribute,
  rowCount: Long,
  percentiles: Option[ArrayData]): ColumnStat
----

`rowToColumnStat`...FIXME

NOTE: `rowToColumnStat` is used when...FIXME
