== [[CreateViewCommand]] CreateViewCommand Logical Command

`CreateViewCommand` is a link:spark-sql-LogicalPlan-RunnableCommand.adoc[logical command] for <<run, creating a view or a table>>.

`CreateViewCommand` is <<creating-instance, created>> to represent the following:

* `CREATE VIEW` SQL statements (with variants)

* `Dataset` operators: <<spark-sql-dataset-operators.adoc#createTempView, createTempView>>, <<spark-sql-dataset-operators.adoc#createOrReplaceTempView, createOrReplaceTempView>>, and <<spark-sql-dataset-operators.adoc#createGlobalTempView, createGlobalTempView>>.

TIP: `CreateViewCommand` is described by `createView` labeled alternative in `statement` expression in `SqlBase.g4` and parsed using link:spark-sql-SparkSqlParser.adoc[SparkSqlParser].

CAUTION: FIXME What's the difference between `CreateTempViewUsing`?

`CreateViewCommand` works with different view types (aka `ViewType`).

.CreateViewCommand's View Types
[options="header",cols="1,2",width="100%"]
|===
| View Type
| Description / Side Effect

| `LocalTempView`
| A session-scoped local temporary view. Available until the session that has created it stops.

When executed, `CreateViewCommand` requests the link:spark-sql-SessionCatalog.adoc#createTempView[current `SessionCatalog` to create a temporary view].

| `GlobalTempView`
| A cross-session global temporary view. Available until a Spark application stops.

When executed, `CreateViewCommand` requests the link:spark-sql-SessionCatalog.adoc#createGlobalTempView[current `SessionCatalog` to create a global view].

| `PersistedView`
| A cross-session persisted view. Available until you it is dropped.

When executed, `CreateViewCommand` checks if the table exists. If it does and replace is enabled `CreateViewCommand` requests the link:spark-sql-SessionCatalog.adoc#alterTable[current `SessionCatalog` to alter a table]. Otherwise, when the table does not exist, `CreateViewCommand` requests the link:spark-sql-SessionCatalog.adoc#createTable[current `SessionCatalog` to create it].
|===

=== [[prepareTable]] `prepareTable` Internal Method

[source, scala]
----
prepareTable(session: SparkSession, analyzedPlan: LogicalPlan): CatalogTable
----

`prepareTable`...FIXME

NOTE: `prepareTable` is used when...FIXME

=== [[run]] `run` Method

[source, scala]
----
run(sparkSession: SparkSession): Seq[Row]
----

NOTE: `run` is part of link:spark-sql-LogicalPlan-RunnableCommand.adoc#run[RunnableCommand Contract] to run a logical command.

`run`...FIXME

=== [[creating-instance]] Creating CreateViewCommand Instance

`CreateViewCommand` takes the following when created:

* [[name]] `TableIdentifier`
* [[userSpecifiedColumns]] User-defined columns (as `Seq[(String, Option[String])]`)
* [[comment]] Optional comment
* [[properties]] Properties (as `Map[String, String]`)
* [[originalText]] Optional DDL statement
* [[child]] Child <<spark-sql-LogicalPlan.adoc#, logical plan>>
* [[allowExisting]] `allowExisting` flag
* [[replace]] `replace` flag
* [[viewType]] `ViewType`
