== [[RowToUnsafeRowDataReaderFactory]] RowToUnsafeRowDataReaderFactory

`RowToUnsafeRowDataReaderFactory` is a link:spark-sql-DataReaderFactory.adoc[DataReaderFactory] of link:spark-sql-UnsafeRow.adoc[UnsafeRows].

`RowToUnsafeRowDataReaderFactory` is <<creating-instance, created>> exclusively when `DataSourceV2ScanExec` physical operator is requested for link:spark-sql-SparkPlan-DataSourceV2ScanExec.adoc#readerFactories[reader factories].

=== [[preferredLocations]] `preferredLocations` Method

[source, scala]
----
preferredLocations: Array[String]
----

NOTE: `preferredLocations` is part of link:spark-sql-DataReaderFactory.adoc#preferredLocations[DataReaderFactory Contract] to...FIXME.

`preferredLocations` simply requests <<rowReaderFactory, rowReaderFactory>> for link:spark-sql-DataReaderFactory.adoc#preferredLocations[preferredLocations].

=== [[createDataReader]] `createDataReader` Method

[source, scala]
----
createDataReader: DataReader[UnsafeRow]
----

NOTE: `createDataReader` is part of link:spark-sql-DataReaderFactory.adoc#createDataReader[DataReaderFactory Contract] to...FIXME.

`createDataReader`...FIXME

=== [[creating-instance]] Creating RowToUnsafeRowDataReaderFactory Instance

`RowToUnsafeRowDataReaderFactory` takes the following when created:

* [[rowReaderFactory]] link:spark-sql-DataReaderFactory.adoc[DataReaderFactory] of link:spark-sql-Row.adoc[rows]
* [[schema]] link:spark-sql-StructType.adoc[Schema]
