== [[ScalarSubquery]] ScalarSubquery Expression

`ScalarSubquery` is a link:spark-sql-Expression-ExecSubqueryExpression.adoc[ExecSubqueryExpression] that returns one row and one column only.

`ScalarSubquery` is <<creating-instance, created>> when...FIXME

[[Unevaluable]]
`ScalarSubquery` link:spark-sql-Expression.adoc#Unevaluable[cannot be evaluated], i.e. produce a value given an internal row.

=== [[updateResult]] `updateResult` Method

[source, scala]
----
updateResult(): Unit
----

NOTE: `updateResult` is part of link:spark-sql-Expression-ExecSubqueryExpression.adoc#updateResult[ExecSubqueryExpression Contract] to...FIXME.

`updateResult`...FIXME

=== [[creating-instance]] Creating ScalarSubquery Instance

`ScalarSubquery` takes the following when created:

* [[plan]] link:spark-sql-LogicalPlan.adoc[Logical plan] of a subquery
* [[children]] Child link:spark-sql-Expression.adoc[expressions] (default: no children)
* [[exprId]] Expression ID (as `ExprId` and defaults to a link:spark-sql-Expression-NamedExpression.adoc#newExprId[new ExprId])
