== [[ClusteredDistribution]] ClusteredDistribution

`ClusteredDistribution` is a link:spark-sql-Distribution.adoc[Distribution] that...FIXME

`ClusteredDistribution` requires that the <<clustering, clustering expressions>> should not be empty (i.e. `Nil`).

`ClusteredDistribution` is <<creating-instance, created>> when...FIXME

=== [[createPartitioning]] `createPartitioning` Method

[source, scala]
----
createPartitioning(numPartitions: Int): Partitioning
----

NOTE: `createPartitioning` is part of link:spark-sql-Distribution.adoc#createPartitioning[Distribution Contract] to...FIXME.

`createPartitioning` creates a `HashPartitioning` for the <<clustering, clustering expressions>> and the input `numPartitions`.

`createPartitioning` reports an `AssertionError` when the <<requiredNumPartitions, number of partitions>> is not the input `numPartitions`.

[options="wrap"]
```
This ClusteredDistribution requires [requiredNumPartitions] partitions, but the actual number of partitions is [numPartitions].
```

=== [[creating-instance]] Creating ClusteredDistribution Instance

`ClusteredDistribution` takes the following when created:

* [[clustering]] Clustering link:spark-sql-Expression.adoc[expressions]
* [[requiredNumPartitions]] Optional number of partitions (default: `None`)
