== [[LeafNode]] LeafNode -- Base Logical Operator with No Child Operators and Optional Statistics

`LeafNode` is the base leaf link:spark-sql-LogicalPlan.adoc[logical operator] with no link:spark-sql-catalyst-TreeNode.adoc#children[child] operators and optional support for <<computeStats, statistics>> for link:spark-sql-cost-based-optimization.adoc[cost-based optimizer] and join query planning.

=== [[computeStats]] Computing Statistics -- `computeStats` Method

[source, scala]
----
computeStats(): Statistics
----

`computeStats` reports an `UnsupportedOperationException`.

NOTE: Logical operators, e.g. `ExternalRDD`, `LogicalRDD` and `DataSourceV2Relation`, or relations, e.g. `HadoopFsRelation` or `BaseRelation`, use link:spark-sql-SQLConf.adoc#spark.sql.defaultSizeInBytes[spark.sql.defaultSizeInBytes] internal property for the default estimated size if the statistics could not be computed.

NOTE: `computeStats` is used exclusively when `SizeInBytesOnlyStatsPlanVisitor` computes the size statistic (in bytes) for a link:spark-sql-LogicalPlan.adoc[logical operator] by default.
