== [[TypeCoercionRule]] TypeCoercionRule -- Contract For Type Coercion Rules

`TypeCoercionRule` is the <<contract, contract>> for Catalyst rules to <<coerceTypes, coerce>> and <<propagateTypes, propagate>> types in logical plans.

[[contract]]
[source, scala]
----
package org.apache.spark.sql.catalyst.analysis

trait TypeCoercionRule extends Rule[LogicalPlan] {
  // only required methods that have no implementation
  // the others follow
  def coerceTypes(plan: LogicalPlan): LogicalPlan
}
----

.(Subset of) TypeCoercionRule Contract
[cols="1,2",options="header",width="100%"]
|===
| Method
| Description

| [[coerceTypes]] `coerceTypes`
| Used when...FIXME
|===

Technically, `TypeCoercionRule` is just a link:spark-sql-catalyst-Rule.adoc[Catalyst rule] for transforming link:spark-sql-LogicalPlan.adoc[logical query plans], i.e. `Rule[LogicalPlan]`.

[[implementations]]
.TypeCoercionRules
[cols="1,2",options="header",width="100%"]
|===
| TypeCoercionRule
| Description

| [[InConversion]] link:spark-sql-Analyzer-InConversion.adoc[InConversion]
|

| _others_
|
|===

=== [[apply]] Applying TypeCoercionRule To Logical Plan (Executing TypeCoercionRule) -- `apply` Method

[source, scala]
----
apply(plan: LogicalPlan): LogicalPlan
----

NOTE: `apply` is part of link:spark-sql-catalyst-Rule.adoc#apply[Rule Contract] to apply a rule to a link:spark-sql-catalyst-TreeNode.adoc[TreeNode], e.g. link:spark-sql-LogicalPlan.adoc[logical plan].

`apply`...FIXME

=== [[propagateTypes]] `propagateTypes` Internal Method

[source, scala]
----
propagateTypes(plan: LogicalPlan): LogicalPlan
----

`propagateTypes`...FIXME

NOTE: `propagateTypes` is used exclusively when `TypeCoercionRule` is <<apply, executed>> (i.e. applied to a link:spark-sql-LogicalPlan.adoc[logical plan]).
