== [[Statistics]] Statistics -- Estimates of Plan Statistics and Query Hints

[[creating-instance]]
`Statistics` holds the estimates of statistics and statistics-related hints of a logical plan:

* [[sizeInBytes]] Total (output) size (in bytes)
* [[rowCount]] Optional estimated number of rows (aka _row count_)
* [[attributeStats]] Column attribute statistics
* [[hints]] Query hints (i.e. `HintInfo`)

CAUTION: FIXME What do the attributes represent exactly? Where do they come from?

NOTE: *Cost statistics*, *plan statistics* or *query statistics* are all synonyms and used interchangeably.

`Statistics` is <<creating-instance, created>> when:

1. link:spark-sql-LogicalPlan-LeafNode.adoc#computeStats[Leaf logical operators] (specifically) and link:spark-sql-LogicalPlanStats.adoc#stats[logical operators] (in general) are requested for cost statistics

1. link:spark-sql-LogicalPlan-HiveTableRelation.adoc#computeStats[HiveTableRelation] and link:spark-sql-LogicalPlan-LogicalRelation.adoc#computeStats[LogicalRelation] are requested for cost statistics (through link:spark-sql-CatalogStatistics.adoc#toPlanStats[CatalogStatistics])

[NOTE]
====
link:spark-sql-CatalogStatistics.adoc[CatalogStatistics] is a "subset" of all possible `Statistics` (as there are no concepts of <<attributeStats, attributes>> and <<hints, broadcast hint>> in link:spark-sql-ExternalCatalog.adoc[metastore]).

`CatalogStatistics` are statistics stored in an external catalog (usually a Hive metastore) and are often referred as *Hive statistics* while `Statistics` represents the *Spark statistics*.
====

[[simpleString]][[toString]]
`Statistics` comes with `simpleString` method that is used for the readable text representation (that `toString` with *Statistics* prefix).

[source, scala]
----
import org.apache.spark.sql.catalyst.plans.logical.Statistics
import org.apache.spark.sql.catalyst.plans.logical.HintInfo
val stats = Statistics(sizeInBytes = 10, rowCount = Some(20), hints = HintInfo(broadcast = true))
scala> println(stats.simpleString)
sizeInBytes=10.0 B, rowCount=20, hints=(broadcast)

scala> println(stats)
Statistics(sizeInBytes=10.0 B, rowCount=20, hints=(broadcast))
----
