== [[HiveClientImpl]] HiveClientImpl -- The One and Only HiveClient

`HiveClientImpl` is the only available link:spark-sql-HiveClient.adoc[HiveClient] in Spark SQL that does/uses...FIXME

`HiveClientImpl` is <<creating-instance, created>> exclusively when `IsolatedClientLoader` is requested to create a `HiveClient`.

When created `HiveClientImpl` is given the location of the default database for the Hive metastore warehouse (aka <<warehouseDir, warehouseDir>>) which is the value of *hive.metastore.warehouse.dir* Hive-specific configuration property (in a Hadoop configuration).

NOTE: The location of the default database for the Hive metastore warehouse is `/user/hive/warehouse` by default.

NOTE: A Hive metastore warehouse (aka `spark-warehouse`) is to persist tables while a Hive metastore (aka `metastore_db`) is to manage the metadata of the persistent relational entities, e.g. databases, tables, columns, partitions.

NOTE: You may be interested in https://issues.apache.org/jira/browse/SPARK-19664[SPARK-19664 put 'hive.metastore.warehouse.dir' in hadoopConf place] if you use Spark before 2.1 (which you should not really as it is not supported anymore).

CAUTION: FIXME How is `hive.metastore.warehouse.dir` related to `spark.sql.warehouse.dir`? `SharedState.warehousePath`? Review https://github.com/apache/spark/pull/16996/files

CAUTION: FIXME How is this Hadoop configuration created?

=== [[readHiveStats]] Reading Statistics from Properties (from Hive's Metastore) -- `readHiveStats` Internal Method

[source, scala]
----
readHiveStats(properties: Map[String, String]): Option[CatalogStatistics]
----

`readHiveStats`...FIXME

NOTE: `readHiveStats` is used when...FIXME

=== [[getTableOption]] Looking Up Table in Metastore -- `getTableOption` Method

[source, scala]
----
def getTableOption(dbName: String, tableName: String): Option[CatalogTable]
----

NOTE: `getTableOption` is a part of link:spark-sql-HiveClient.adoc#getTableOption[HiveClient Contract] to...FIXME.

`getTableOption`...FIXME

=== [[creating-instance]] Creating HiveClientImpl Instance

`HiveClientImpl` takes the following when created:

* [[version]] `HiveVersion`
* [[warehouseDir]] Location of the default database for the Hive metastore warehouse if defined (aka `warehouseDir`)
* [[sparkConf]] `SparkConf`
* [[hadoopConf]] Hadoop configuration
* [[extraConfig]] Extra configuration
* [[initClassLoader]] Initial `ClassLoader`
* [[clientLoader]] `IsolatedClientLoader`

`HiveClientImpl` initializes the <<internal-registries, internal registries and counters>>.
